version: 0.2
phases:
  install:
    commands:
      - mvn clean package shade:shade
      - export BUCKET=aws-codepipeline-lambda-sources
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml